openapi: 3.0.0
info:
  title: Restaurant API
  description: un API pour la gestion des clients dans un restaurant
  version: 1.0.0
servers:
  - url: https://localhost.std22122.com
paths:
  /customers:
    get:
      summary: Récupérer la liste des clients
      parameters:
        - name: page
          in: query
          required: true
          description: le numero de la page a recuperer
          schema:
            type: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: le nombre de clients par page
          schema:
            type: integer
            example: 23
      responses:
        '200':
          description: Liste des clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer
