openapi: 3.0.0
info:
  title: Restaurant API
  description: Une API pour la gestion des clients dans un restaurant
  version: 1.0.0
servers:
  - url: https://localhost.std22122.com
paths:
  /customers:
    get:
      summary: Récupérer la liste des clients
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Le numéro de la page à récupérer.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Le nombre d'éléments par page.
      responses:
        '200':
          description: Liste des clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Créer de nouveaux clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Clients créés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

