openapi: 3.0.0
info:
  title: Restaurant API
  description: Une API pour la gestion d'un restaurant, incluant les clients, les plats et les commandes
  version: 1.0.0
servers:
  - url: https://localhost.std22122.com
paths:
  /customers/{customerId}/orders:
    get:
      summary: Récupérer la liste des commandes d'un client
      parameters:
        - name: customerId
          in: path
          required: true
          description: Identifiant du client
      responses:
        '200':
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Créer une nouvelle commande pour un client
      parameters:
        - name: customerId
          in: path
          required: true
          description: Identifiant du client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreation'
      responses:
        '201':
          description: Commande créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      summary: Modifier une commande existante d'un client
      parameters:
        - name: customerId
          in: path
          required: true
          description: Identifiant du client
        - name: orderId
          in: path
          required: true
          description: Identifiant de la commande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Commande modifiée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du client
        name:
          type: string
          description: Nom du client
        email:
          type: string
          description: Adresse email du client
        phone:
          type: string
          description: Numéro de téléphone du client
      required:
        - id
        - name
        - email
    Meal:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du plat
        name:
          type: string
          description: Nom du plat
        price:
          type: number
          format: decimal
          description: Prix du plat
      required:
        - name
        - price
    Order:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de la commande
        reference:
          type: string
          description: Référence de la commande
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: '#/components/schemas/Meal'
              quantity:
                type: integer
        orderDatetime:
          type: string
          format: date-time
          description: Date et heure de la commande
      required:
        - reference
        - meals
        - orderDatetime
    OrderCreation:
      type: object
      properties:
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: '#/components/schemas/Meal'
              quantity:
                type: integer
      required:
        - meals