openapi: 3.0.0
info:
  title: Customer API
  description: Une API pour la gestion des clients dans un restaurant
  version: 1.0.0
servers:
  - url: https://localhost.std22122.com
paths:
  /customers:
    get:
      summary: Récupérer la liste des clients
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Le numéro de la page à récupérer.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Le nombre d'éléments par page.
      responses:
        '200':
          description: Liste des clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Créer de nouveaux clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Clients créés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    put:
      summary: Modifier un client existant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Client modifié avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    delete:
      summary: Supprimer des clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: Liste des identifiants des clients à supprimer.
      responses:
        '200':
          description: Clients supprimés avec succès

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du client
        name:
          type: string
          description: Nom du client
        email:
          type: string
          description: Adresse email du client
        phone:
          type: string
          description: Numéro de téléphone du client
      required:
        - id
        - name
        - email