openapi: 3.0.0
info:
  title: Meal API
  description: Une API pour la gestion des plats dans un restaurant
  version: 1.0.0
servers:
  - url: https://localhost.std22122.com
paths:
  /meals:
    get:
      summary: Récupérer la liste des plats
      responses:
        '200':
          description: Liste des plats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Créer un nouveau plat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MealCreation'
      responses:
        '201':
          description: Plats créés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    put:
      summary: Modifier un plat existant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
      responses:
        '200':
          description: Plat modifié avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    delete:
      summary: Supprimer des plats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: Liste des identifiants des plats à supprimer.
      responses:
        '200':
          description: Plats supprimés avec succès

components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du plat
        name:
          type: string
          description: Nom du plat
        price:
          type: number
          format: decimal
          description: Prix du plat
      required:
        - name
        - price
    MealCreation:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: decimal
      required:
        - name
        - price